### PR TITLE
C support

### PR DESCRIPTION
**Pull request by saladuit**
In line 18  of c.lua I hard coded the path to all of the coverage information. I really don't know what I did wrong to fix that, but other than that it works!

### CODE REVIEW

**Comment by saladuit** [comment]
This fixed my issue on #21 for me

**Comment by andythigpen** [comment]
Thank you for the PR.

Would it make sense to use `config_alias` for the C & C++ implementations like the current Typescript/Javascript implementations (ex [here](https://github.com/andythigpen/nvim-coverage/blob/fd44fde75468ddc8d72c7a64812c6d88826a3301/lua/coverage/languages/typescript.lua#L7)) ? The only difference seems to be the default `coverage_file` name in the config.

**Comment by saladuit** [comment]
You're probably right! This was my first time coding something in lua, I'd always used neovim with .vim files. But it's quite easy in comparison to normal vim files. Let me see if I can make a quick fix.

**Comment by saladuit** [comment]
@andythigpen This should do it

**Pull request merged**
